### ISSUE TITLE
Вопросы о Private Test submission

### ISSUE THREAD

**Issue by victorbocharov** [dialogue-evaluation/GramEval2020#14]
Когда откроется возможность подавать результаты обработки Private Test?
Сколько времени она будет открыта?
Сколько попыток можно будет сделать?
Которая из попыток будет засчитана (лучшая или последняя)?

**Comment by TatianaShavrina** [comment]
Все актуальные даты соревнования лучше смотреть на CodaLab https://competitions.codalab.org/competitions/22902

Приватный тест будет открыт сутки, с 22 оп 23 февраля по мск, за эти сутки необходимо сделать сабмишен (максимально 999 раз).
Результат будет доступен участнику сразу, по умолчанию выбирается лучший вариант. Также нужно будет отправить в теч нескольких дней ссылку на репозиторий с решением.
