### ISSUE TITLE
в отчёте conll18_ud_eval.py поехало форматирование

### ISSUE THREAD

**Issue by victorbocharov** [dialogue-evaluation/GramEval2020#19]
Нет разделения на колонки пробелами и перевода строки после шапки.
Проблема не большая, но читать не очень удобно.

**Comment by TatianaShavrina** [comment]
Спасибо, сегодня вечером поправим.

**Comment by TatianaShavrina** [comment]
поправила! Залейте любой submission еще раз -- и в conll.txt будет построчное отображение

Заняло немного больше времени, так как на CodaLab python 2.6
