### ISSUE TITLE
сломался кодалаб

### ISSUE THREAD

**Issue by victorbocharov** [dialogue-evaluation/GramEval2020#22]
Пишет вот такое:

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpE1dxDY/run/program/evaluate.py", line 238, in 
    main()
  File "/tmp/codalab/tmpE1dxDY/run/program/evaluate.py", line 119, in main
    test_dic = extract_sents(open(os.path.join(test_dir,'GramEval_private_test.conllu'), 'r').read(), index_dic)
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmpE1dxDY/run/input/res/GramEval_private_test.conllu'

**Comment by TatianaShavrina** [comment]
Это значит,что сломана исходная локализация. Ломать нельзя , иначе золотая выборка не извлечется корректно.

**Comment by victorbocharov** [comment]
Я заливал данные, которые утром нормально оценивались.
Текст ошибки (No such file or directory) больше похож на какие-то проблемы на сервере.

**Comment by TatianaShavrina** [comment]
А, понятно. Назовите файл в своём архиве сабмита GramEval_private_test.conllu, как в архиве бейзлайна .
