### ISSUE TITLE
BibTex статьи организаторов

### ISSUE THREAD

**Issue by victorbocharov** [dialogue-evaluation/GramEval2020#27]
В телеграм канале дан BibTex статьи организаторов без указания имён авторов:

@inproceedings{grameval2020,
title={{GramEval 2020 Shared Task: Russian Full Morphology and Dependency Parsing}},
author={},
booktitle={Computational Linguistics and Intellectual Technologies: Papers from the Annual Conference ``Dialogue''},
year={2020}, volume = {20}
}

Так и должно быть?

**Comment by TatianaShavrina** [comment]
Спасибо за вопрос! Указала авторов:

@inproceedings{grameval2020,
title={{GramEval 2020 Shared Task: Russian Full Morphology and Dependency Parsing}},
author={Lyashevskaya, Olga; Shavrina, Tatiana; Trofimov, igor; Vlasova, Natalia},
booktitle={Computational Linguistics and Intellectual Technologies: Papers from the Annual Conference ``Dialogue''},
year={2020}, volume = {20}
}

**Comment by victorbocharov** [comment]
Спасибо! У меня компилятор отругался на "слишком много запятых". Вот так работает:

@inproceedings{grameval2020,
title={{GramEval 2020 Shared Task: Russian Full Morphology and Dependency Parsing}},
author={Lyashevskaya, Olga and Shavrina, Tatiana and Trofimov, Igor and Vlasova, Natalia},
booktitle={Computational Linguistics and Intellectual Technologies: Papers from the Annual Conference ``Dialogue''},
year={2020}, volume = {20}
}
